# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MQTT_TEST.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from pathlib import Path
from PyQt5 import QAxContainer
from PyQt5.QtCore import Qt
from PyQt5.QtWidgets import QWidget, QVBoxLayout, QPushButton, QLineEdit, QApplication


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1024, 600)
        MainWindow.setMinimumSize(QtCore.QSize(1024, 600))
        MainWindow.setMaximumSize(QtCore.QSize(1024, 600))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setMinimumSize(QtCore.QSize(1024, 600))
        self.centralwidget.setMaximumSize(QtCore.QSize(1024, 500))
        self.centralwidget.setObjectName("centralwidget")
        self.stackedWidget = QtWidgets.QStackedWidget(self.centralwidget)
        self.stackedWidget.setGeometry(QtCore.QRect(0, -10, 1024, 600))
        self.stackedWidget.setObjectName("stackedWidget")
        self.HOME = QtWidgets.QWidget()
        self.HOME.setObjectName("HOME")
        self.widget = QtWidgets.QWidget(self.HOME)
        self.widget.setGeometry(QtCore.QRect(0, 0, 1021, 610))
        self.widget.setObjectName("widget")
        self.gridLayout = QtWidgets.QGridLayout(self.widget)
        self.gridLayout.setContentsMargins(10, 10, 10, 20)
        self.gridLayout.setSpacing(10)
        self.gridLayout.setObjectName("gridLayout")
        self.Home_Button_Learn = QtWidgets.QPushButton(self.widget)
        self.Home_Button_Learn.setMinimumSize(QtCore.QSize(100, 280))
        self.Home_Button_Learn.setStyleSheet("background-color: rgb(85, 170, 255);")
        self.Home_Button_Learn.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("Icon/LyThuet.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Home_Button_Learn.setIcon(icon)
        self.Home_Button_Learn.setIconSize(QtCore.QSize(100, 100))
        self.Home_Button_Learn.setObjectName("Home_Button_Learn")
        self.gridLayout.addWidget(self.Home_Button_Learn, 0, 0, 1, 1)
        self.Home_Button_Test = QtWidgets.QPushButton(self.widget)
        self.Home_Button_Test.setMinimumSize(QtCore.QSize(100, 280))
        self.Home_Button_Test.setAutoFillBackground(False)
        self.Home_Button_Test.setStyleSheet("background-color: rgb(255, 170, 0);")
        self.Home_Button_Test.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("Icon/test_icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Home_Button_Test.setIcon(icon1)
        self.Home_Button_Test.setIconSize(QtCore.QSize(150, 150))
        self.Home_Button_Test.setObjectName("Home_Button_Test")
        self.gridLayout.addWidget(self.Home_Button_Test, 0, 1, 1, 1)
        self.Home_Button_Setting = QtWidgets.QPushButton(self.widget)
        self.Home_Button_Setting.setMinimumSize(QtCore.QSize(100, 280))
        self.Home_Button_Setting.setAutoFillBackground(False)
        self.Home_Button_Setting.setStyleSheet("background-color: rgb(255, 170, 0);")
        self.Home_Button_Setting.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("Icon/setting_icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Home_Button_Setting.setIcon(icon2)
        self.Home_Button_Setting.setIconSize(QtCore.QSize(100, 100))
        self.Home_Button_Setting.setCheckable(False)
        self.Home_Button_Setting.setAutoRepeat(False)
        self.Home_Button_Setting.setObjectName("Home_Button_Setting")
        self.gridLayout.addWidget(self.Home_Button_Setting, 1, 0, 1, 1)
        self.Home_Button_Information = QtWidgets.QPushButton(self.widget)
        self.Home_Button_Information.setMinimumSize(QtCore.QSize(100, 280))
        self.Home_Button_Information.setStyleSheet("background-color: rgb(85, 170, 255);")
        self.Home_Button_Information.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("Icon/infor.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Home_Button_Information.setIcon(icon3)
        self.Home_Button_Information.setIconSize(QtCore.QSize(120, 120))
        self.Home_Button_Information.setObjectName("Home_Button_Information")
        self.gridLayout.addWidget(self.Home_Button_Information, 1, 1, 1, 1)
        self.stackedWidget.addWidget(self.HOME)
        self.Screen_Learn = QtWidgets.QWidget()
        self.Screen_Learn.setObjectName("Screen_Learn")
        self.Learn_Button_Back = QtWidgets.QPushButton(self.Screen_Learn)
        self.Learn_Button_Back.setGeometry(QtCore.QRect(470, 540, 71, 61))
        self.Learn_Button_Back.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("Icon/back_icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Learn_Button_Back.setIcon(icon4)
        self.Learn_Button_Back.setIconSize(QtCore.QSize(50, 50))
        self.Learn_Button_Back.setObjectName("Learn_Button_Back")

        self.WebBrowser = QAxContainer.QAxWidget(self.Screen_Learn)
        self.WebBrowser.setGeometry(QtCore.QRect(0, 0, 1024, 540))
        self.WebBrowser.setFocusPolicy(Qt.StrongFocus)
        self.WebBrowser.setControl("{8856F961-340A-11D0-A96B-00C04FD705A2}")
        self.WebBrowser.setObjectName("Browser")
        self.stackedWidget.addWidget(self.Screen_Learn)
        self.stackedWidget.addWidget(self.Screen_Learn)
        self.screen_Test = QtWidgets.QWidget()
        self.screen_Test.setObjectName("screen_Test")
        self.stackedWidget.addWidget(self.screen_Test)
        self.screen_Setting = QtWidgets.QWidget()
        self.screen_Setting.setObjectName("screen_Setting")
        self.stackedWidget.addWidget(self.screen_Setting)
        self.screen_Information = QtWidgets.QWidget()
        self.screen_Information.setObjectName("screen_Information")
        self.stackedWidget.addWidget(self.screen_Information)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(2)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
